# Site settings
title: Coding && Programming || The Art of bringing ideas to life 
header-img: img/home-bg.png
email: ivanpilot@gmail.com
copyright_name: ivanpilot
description: > # this means to ignore newlines until "baseurl:"
  The empirical path and experience of a developer (Ruby, RoR, JS, Angular, etc.)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ivanpilot
learn_profile: ivanpilot
email_username: ivanpilot@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
